# Ninja build file generation for nixnative
#
# Generates ninja build file content at Nix evaluation time.
# The resulting file is consumed by nix-ninja at build time.
#
{ lib }:

let
  inherit (lib) concatStringsSep concatMapStringsSep escapeShellArg;

  # Escape a string for use in ninja files
  # Ninja uses $ as escape character: $$ for literal $, $: for :, etc.
  escapeNinja = s:
    builtins.replaceStrings
      [ "$" "\n" " " ":" ]
      [ "$$" "$\n" "$ " "$:" ]
      s;

  # Format include flags
  formatIncludes = dirs:
    concatMapStringsSep " " (d: "-I${escapeNinja (toString d)}") dirs;

  # Format define flags
  formatDefines = defines:
    concatMapStringsSep " " (d:
      if builtins.isString d then "-D${escapeNinja d}"
      else if d ? name && d ? value then "-D${escapeNinja d.name}=${escapeNinja (toString d.value)}"
      else if d ? name then "-D${escapeNinja d.name}"
      else throw "Invalid define: ${builtins.toJSON d}"
    ) defines;

  # Format generic flags
  formatFlags = flags:
    concatMapStringsSep " " escapeNinja flags;

  # Generate a compile rule for a specific language
  mkCompileRule = { name, compiler, defaultFlags, depfileFlag ? "-MF" }: ''
    rule ${name}
      command = ${compiler} $FLAGS ${depfileFlag} $out.d -MD -c $in -o $out
      deps = gcc
      depfile = $out.d
      description = Compiling $in
  '';

  # Generate a link rule for executables
  mkLinkExeRule = { compiler, linkerFlag }: ''
    rule link_exe
      command = ${compiler} ${linkerFlag} $in $LDFLAGS -o $out
      description = Linking executable $out
  '';

  # Generate a link rule for shared libraries
  mkLinkSharedRule = { compiler, linkerFlag }: ''
    rule link_shared
      command = ${compiler} ${linkerFlag} -shared $in $LDFLAGS -o $out
      description = Linking shared library $out
  '';

  # Generate an archive rule for static libraries
  mkArchiveRule = { ar, ranlib }: ''
    rule archive
      command = rm -f $out && ${ar} rcs $out $in && ${ranlib} $out
      description = Creating static library $out
  '';

  # Generate a build statement for a source file
  mkBuildStatement = { source, rule, objectName, flags }: ''
    build ${objectName}: ${rule} ${escapeNinja (toString source.store)}/${escapeNinja source.relNorm}
      FLAGS = ${flags}
  '';

in
{
  inherit escapeNinja formatIncludes formatDefines formatFlags;
  inherit mkCompileRule mkLinkExeRule mkLinkSharedRule mkArchiveRule mkBuildStatement;

  # Generate complete ninja file for an executable
  generateExecutable = {
    name,
    sources,       # [ { store, relNorm, objectName, lang } ]
    toolchain,
    includeDirs,   # [ path ]
    defines,       # [ string or { name, value? } ]
    compileFlags,  # [ string ]
    langFlags,     # { c = [...]; cpp = [...]; }
    ldflags,       # [ string ]
  }:
    let
      cCompiler = toolchain.getCompilerForLanguage "c";
      cxxCompiler = toolchain.getCompilerForLanguage "cpp";
      linkerFlag = toolchain.linker.driverFlag or "";

      # Get C++ runtime library path for RPATH
      cxxRuntimeLibPath = toolchain.cxxRuntimeLibPath or null;
      rpathFlags = if cxxRuntimeLibPath != null
        then [ "-Wl,-rpath,${cxxRuntimeLibPath}" ]
        else [];

      # Separate sources by language
      cSources = builtins.filter (s: s.lang == "c") sources;
      cppSources = builtins.filter (s: s.lang == "cpp") sources;

      # Build flags for each language
      cFlags = formatFlags (compileFlags ++ (langFlags.c or []))
        + " " + formatIncludes includeDirs
        + " " + formatDefines defines;
      cppFlags = formatFlags (compileFlags ++ (langFlags.cpp or []))
        + " " + formatIncludes includeDirs
        + " " + formatDefines defines;

      allObjects = map (s: s.objectName) sources;
    in
    ''
      # Auto-generated by nixnative
      # Target: ${name}

      ${mkCompileRule {
        name = "cc";
        compiler = cCompiler;
        defaultFlags = "";
      }}

      ${mkCompileRule {
        name = "cxx";
        compiler = cxxCompiler;
        defaultFlags = "";
      }}

      ${mkLinkExeRule {
        compiler = cxxCompiler;
        inherit linkerFlag;
      }}

      # C sources
      ${concatMapStringsSep "\n" (src:
        mkBuildStatement {
          source = src;
          rule = "cc";
          objectName = src.objectName;
          flags = cFlags;
        }
      ) cSources}

      # C++ sources
      ${concatMapStringsSep "\n" (src:
        mkBuildStatement {
          source = src;
          rule = "cxx";
          objectName = src.objectName;
          flags = cppFlags;
        }
      ) cppSources}

      # Link executable
      build ${name}: link_exe ${concatStringsSep " " allObjects}
        LDFLAGS = ${formatFlags (rpathFlags ++ ldflags)}

      default ${name}
    '';

  # Generate complete ninja file for a static library (compile only, no link)
  generateStaticLib = {
    name,
    sources,
    toolchain,
    includeDirs,
    defines,
    compileFlags,
    langFlags,
  }:
    let
      cCompiler = toolchain.getCompilerForLanguage "c";
      cxxCompiler = toolchain.getCompilerForLanguage "cpp";

      cSources = builtins.filter (s: s.lang == "c") sources;
      cppSources = builtins.filter (s: s.lang == "cpp") sources;

      cFlags = formatFlags (compileFlags ++ (langFlags.c or []))
        + " " + formatIncludes includeDirs
        + " " + formatDefines defines;
      cppFlags = formatFlags (compileFlags ++ (langFlags.cpp or []))
        + " " + formatIncludes includeDirs
        + " " + formatDefines defines;

      allObjects = map (s: s.objectName) sources;
      archiveName = "lib${name}.a";
      ar = toolchain.bintools.ar;
      ranlib = toolchain.bintools.ranlib;
    in
    ''
      # Auto-generated by nixnative
      # Target: ${name} (static library)

      ${mkCompileRule {
        name = "cc";
        compiler = cCompiler;
        defaultFlags = "";
      }}

      ${mkCompileRule {
        name = "cxx";
        compiler = cxxCompiler;
        defaultFlags = "";
      }}

      ${mkArchiveRule { inherit ar ranlib; }}

      # C sources
      ${concatMapStringsSep "\n" (src:
        mkBuildStatement {
          source = src;
          rule = "cc";
          objectName = src.objectName;
          flags = cFlags;
        }
      ) cSources}

      # C++ sources
      ${concatMapStringsSep "\n" (src:
        mkBuildStatement {
          source = src;
          rule = "cxx";
          objectName = src.objectName;
          flags = cppFlags;
        }
      ) cppSources}

      # Create archive
      build ${archiveName}: archive ${concatStringsSep " " allObjects}

      default ${archiveName}
    '';

  # Generate complete ninja file for a shared library
  generateSharedLib = {
    name,
    sources,
    toolchain,
    includeDirs,
    defines,
    compileFlags,
    langFlags,
    ldflags,
  }:
    let
      cCompiler = toolchain.getCompilerForLanguage "c";
      cxxCompiler = toolchain.getCompilerForLanguage "cpp";
      linkerFlag = toolchain.linker.driverFlag or "";

      # Get C++ runtime library path for RPATH
      cxxRuntimeLibPath = toolchain.cxxRuntimeLibPath or null;
      rpathFlags = if cxxRuntimeLibPath != null
        then [ "-Wl,-rpath,${cxxRuntimeLibPath}" ]
        else [];

      cSources = builtins.filter (s: s.lang == "c") sources;
      cppSources = builtins.filter (s: s.lang == "cpp") sources;

      # Add -fPIC for shared libraries
      cFlags = formatFlags (["-fPIC"] ++ compileFlags ++ (langFlags.c or []))
        + " " + formatIncludes includeDirs
        + " " + formatDefines defines;
      cppFlags = formatFlags (["-fPIC"] ++ compileFlags ++ (langFlags.cpp or []))
        + " " + formatIncludes includeDirs
        + " " + formatDefines defines;

      allObjects = map (s: s.objectName) sources;
      sharedLibName = "lib${name}.so";
    in
    ''
      # Auto-generated by nixnative
      # Target: ${name} (shared library)

      ${mkCompileRule {
        name = "cc";
        compiler = cCompiler;
        defaultFlags = "";
      }}

      ${mkCompileRule {
        name = "cxx";
        compiler = cxxCompiler;
        defaultFlags = "";
      }}

      ${mkLinkSharedRule {
        compiler = cxxCompiler;
        inherit linkerFlag;
      }}

      # C sources
      ${concatMapStringsSep "\n" (src:
        mkBuildStatement {
          source = src;
          rule = "cc";
          objectName = src.objectName;
          flags = cFlags;
        }
      ) cSources}

      # C++ sources
      ${concatMapStringsSep "\n" (src:
        mkBuildStatement {
          source = src;
          rule = "cxx";
          objectName = src.objectName;
          flags = cppFlags;
        }
      ) cppSources}

      # Link shared library
      build ${sharedLibName}: link_shared ${concatStringsSep " " allObjects}
        LDFLAGS = ${formatFlags (rpathFlags ++ ldflags)}

      default ${sharedLibName}
    '';
}
