# Ninja build file generation for nixnative
#
# Generates ninja build file content at Nix evaluation time.
# The resulting file is consumed by nix-ninja at build time.
#
{ lib }:

let
  inherit (lib) concatStringsSep concatMapStringsSep;

  # Escape a string for use in ninja files
  # Ninja uses $ as escape character: $$ for literal $, $: for :, etc.
  escapeNinja = s:
    builtins.replaceStrings
      [ "$" "\n" " " ":" ]
      [ "$$" "$\n" "$ " "$:" ]
      s;

  # Format include flags
  formatIncludes = dirs:
    concatMapStringsSep " " (d: "-I${escapeNinja (toString d)}") dirs;

  # Format define flags
  formatDefines = defines:
    concatMapStringsSep " " (d:
      if builtins.isString d then "-D${escapeNinja d}"
      else if d ? name && d ? value then "-D${escapeNinja d.name}=${escapeNinja (toString d.value)}"
      else if d ? name then "-D${escapeNinja d.name}"
      else throw "Invalid define: ${builtins.toJSON d}"
    ) defines;

  # Format generic flags
  formatFlags = flags:
    concatMapStringsSep " " escapeNinja flags;

  # Generate a compile rule for a specific language
  mkCompileRule = { name, compiler }: ''
    rule ${name}
      command = ${compiler} $FLAGS -MF $out.d -MD -c $in -o $out
      deps = gcc
      depfile = $out.d
      description = Compiling $in
  '';

  # Generate a build statement for a source file
  mkBuildStatement = { source, rule, objectName, flags }: ''
    build ${objectName}: ${rule} ${escapeNinja (toString source.store)}/${escapeNinja source.relNorm}
      FLAGS = ${flags}
  '';

  # Common setup for all generators - extracts compilers, filters sources, formats flags
  prepareCompilation = { name, sources, toolchain, includeDirs, defines, compileFlags, languageFlags, extraCFlags ? [] }:
    let
      cCompiler = toolchain.getCompilerForLanguage "c";
      cxxCompiler = toolchain.getCompilerForLanguage "cpp";

      cSources = builtins.filter (s: s.lang == "c") sources;
      cppSources = builtins.filter (s: s.lang == "cpp") sources;

      baseIncludeDefines = formatIncludes includeDirs + " " + formatDefines defines;
      cFlags = formatFlags (extraCFlags ++ compileFlags ++ (languageFlags.c or [])) + " " + baseIncludeDefines;
      cppFlags = formatFlags (extraCFlags ++ compileFlags ++ (languageFlags.cpp or [])) + " " + baseIncludeDefines;

      allObjects = map (s: s.objectName) sources;

      compileRules = ''
        ${mkCompileRule { name = "cc"; compiler = cCompiler; }}

        ${mkCompileRule { name = "cxx"; compiler = cxxCompiler; }}
      '';

      buildStatements = ''
        # C sources
        ${concatMapStringsSep "\n" (src:
          mkBuildStatement { source = src; rule = "cc"; objectName = src.objectName; flags = cFlags; }
        ) cSources}

        # C++ sources
        ${concatMapStringsSep "\n" (src:
          mkBuildStatement { source = src; rule = "cxx"; objectName = src.objectName; flags = cppFlags; }
        ) cppSources}
      '';
    in {
      inherit cxxCompiler allObjects compileRules buildStatements;
      linkerFlag = toolchain.linker.driverFlag or "";
      cxxRuntimeLibPath = toolchain.cxxRuntimeLibPath or null;
    };

in
{
  inherit escapeNinja formatIncludes formatDefines formatFlags mkBuildStatement;

  # Generate complete ninja file for an executable
  generateExecutable = {
    name,
    sources,
    toolchain,
    includeDirs,
    defines,
    compileFlags,
    languageFlags,
    linkFlags,
  }:
    let
      prep = prepareCompilation { inherit name sources toolchain includeDirs defines compileFlags languageFlags; };
      rpathFlags = if prep.cxxRuntimeLibPath != null
        then [ "-Wl,-rpath,${prep.cxxRuntimeLibPath}" ]
        else [];
    in
    ''
      # Auto-generated by nixnative
      # Target: ${name}

      ${prep.compileRules}

      rule link_exe
        command = ${prep.cxxCompiler} ${prep.linkerFlag} $in $LDFLAGS -o $out
        description = Linking executable $out

      ${prep.buildStatements}

      # Link executable
      build ${name}: link_exe ${concatStringsSep " " prep.allObjects}
        LDFLAGS = ${formatFlags (rpathFlags ++ linkFlags)}

      default ${name}
    '';

  # Generate complete ninja file for a static library
  generateStaticLib = {
    name,
    sources,
    toolchain,
    includeDirs,
    defines,
    compileFlags,
    languageFlags,
  }:
    let
      prep = prepareCompilation { inherit name sources toolchain includeDirs defines compileFlags languageFlags; };
      archiveName = "lib${name}.a";
      ar = toolchain.bintools.ar;
      ranlib = toolchain.bintools.ranlib;
    in
    ''
      # Auto-generated by nixnative
      # Target: ${name} (static library)

      ${prep.compileRules}

      rule archive
        command = rm -f $out && ${ar} rcs $out $in && ${ranlib} $out
        description = Creating static library $out

      ${prep.buildStatements}

      # Create archive
      build ${archiveName}: archive ${concatStringsSep " " prep.allObjects}

      default ${archiveName}
    '';

  # Generate complete ninja file for a shared library
  generateSharedLib = {
    name,
    sources,
    toolchain,
    includeDirs,
    defines,
    compileFlags,
    languageFlags,
    linkFlags,
  }:
    let
      # Pass -fPIC as extra compile flag for shared libraries
      prep = prepareCompilation {
        inherit name sources toolchain includeDirs defines compileFlags languageFlags;
        extraCFlags = [ "-fPIC" ];
      };
      rpathFlags = if prep.cxxRuntimeLibPath != null
        then [ "-Wl,-rpath,${prep.cxxRuntimeLibPath}" ]
        else [];
      sharedLibName = "lib${name}.so";
    in
    ''
      # Auto-generated by nixnative
      # Target: ${name} (shared library)

      ${prep.compileRules}

      rule link_shared
        command = ${prep.cxxCompiler} ${prep.linkerFlag} -shared $in $LDFLAGS -o $out
        description = Linking shared library $out

      ${prep.buildStatements}

      # Link shared library
      build ${sharedLibName}: link_shared ${concatStringsSep " " prep.allObjects}
        LDFLAGS = ${formatFlags (rpathFlags ++ linkFlags)}

      default ${sharedLibName}
    '';
}
