# Binary blob tool plugin for nixnative
#
# Embeds binary/text files as C source code, similar to objcopy -I binary.
# Creates symbols compatible with objcopy's naming convention:
#   _binary_<name>_start - pointer to start of data
#   _binary_<name>_end   - pointer to end of data
#   _binary_<name>_size  - size of data (as a symbol, not a variable)
#
# Example usage:
#   tools = [
#     (native.binaryBlob.run {
#       inputFiles = [ "usage.txt" "help.txt" ];
#     })
#   ];
#
# This generates C files that can be used like:
#   extern const char _binary_usage_txt_start[];
#   extern const char _binary_usage_txt_end[];
#   size_t size = _binary_usage_txt_end - _binary_usage_txt_start;
#
{
  pkgs,
  lib,
  mkTool,
}:

let
  inherit (lib)
    concatStringsSep
    replaceStrings
    removeSuffix
    ;

  # Convert a filename to a valid C identifier matching objcopy's convention
  # objcopy replaces . and / and - with _
  toSymbolName =
    file:
    let
      # Get just the filename, not the path
      baseName = builtins.baseNameOf file;
    in
    replaceStrings [ "." "/" "-" " " ] [ "_" "_" "_" "_" ] baseName;

  # Generate C source code for a binary blob
  # This creates the same symbols as objcopy -I binary
  generateBlobSource =
    {
      file,
      symbolName,
      alignTo ? 16, # Alignment for the data
    }:
    ''
      /* Generated by nixnative binary-blob tool */
      /* Source file: ${file} */

      #include <stddef.h>

      /* Data aligned to ${toString alignTo} bytes for optimal access */
      __attribute__((aligned(${toString alignTo})))
      const unsigned char _binary_${symbolName}_start[] = {
      #include "${symbolName}.inc"
      };

      /* End pointer - points one past the last byte */
      const unsigned char* const _binary_${symbolName}_end =
          _binary_${symbolName}_start + sizeof(_binary_${symbolName}_start);

      /* Size as a regular variable (objcopy uses a symbol, but this is more portable) */
      const size_t _binary_${symbolName}_size = sizeof(_binary_${symbolName}_start);
    '';

  # Binary blob transformation
  binaryBlobTransform =
    {
      inputFiles,
      root,
      config,
    }:
    let
      alignTo = config.alignTo or 16;

      # Convert input files to paths
      files = map (
        f:
        if builtins.isAttrs f && f ? rel then
          f.rel
        else if builtins.isString f then
          f
        else
          throw "nixnative/binary-blob: input files must be strings or attrsets with 'rel'"
      ) inputFiles;

      filesStr = concatStringsSep " " (map lib.escapeShellArg files);
    in
    pkgs.runCommand "binary-blob-gen"
      {
        nativeBuildInputs = [ pkgs.xxd ];
        src = root;
      }
      ''
        set -euo pipefail
        mkdir -p $out

        cd $src

        for file in ${filesStr}; do
          # Get base filename and create symbol name
          basename=$(basename "$file")
          # Replace . / - and space with _
          symbolname=$(echo "$basename" | sed 's/[.\/ -]/_/g')

          echo "Generating blob for: $file -> $symbolname"

          # Generate the hex data
          hexdata=$(xxd -i < "$file")

          # Generate the C source file with inlined data (no separate .inc file)
          # Use extern "C" to ensure C linkage since nixnative compiles with clang++
          cat > "$out/$symbolname.c" << BLOB_EOF
        /* Generated by nixnative binary-blob tool */
        /* Source file: $file */

        #include <stddef.h>

        #ifdef __cplusplus
        extern "C" {
        #endif

        /* Data aligned to ${toString alignTo} bytes for optimal access
         * __attribute__((used)) prevents the compiler from optimizing these away
         * extern gives external linkage (const has internal linkage in C++ by default) */
        __attribute__((used, aligned(${toString alignTo})))
        extern const unsigned char _binary_''${symbolname}_start[] = {
        $hexdata
        };

        /* End pointer - points one past the last byte */
        __attribute__((used))
        extern const unsigned char* const _binary_''${symbolname}_end =
            _binary_''${symbolname}_start + sizeof(_binary_''${symbolname}_start);

        /* Size as a regular variable (objcopy uses a symbol, but this is more portable) */
        __attribute__((used))
        extern const size_t _binary_''${symbolname}_size = sizeof(_binary_''${symbolname}_start);

        #ifdef __cplusplus
        }
        #endif
        BLOB_EOF
        done
      '';

  # Binary blob output schema
  binaryBlobOutputs =
    {
      drv,
      inputFiles,
      config,
    }:
    let
      # Generate output entries for each input file
      mkOutput =
        file:
        let
          fileName =
            if builtins.isAttrs file && file ? rel then
              file.rel
            else
              file;
          baseName = builtins.baseNameOf fileName;
          symbolName = replaceStrings [ "." "/" "-" " " ] [ "_" "_" "_" "_" ] baseName;
        in
        { rel = "${symbolName}.c"; path = "${drv}/${symbolName}.c"; };
    in
    {
      outputs = map mkOutput inputFiles;
      includeDirs = [ ]; # No include dirs needed - data is inlined
      defines = [ ];
      compileFlags = [ ];
      linkFlags = [ ];
    };

in
rec {
  # ==========================================================================
  # Binary Blob Tool
  # ==========================================================================

  binaryBlob = mkTool {
    name = "binary-blob";

    transform = binaryBlobTransform;
    outputs = binaryBlobOutputs;

    # No runtime dependencies
    dependencies = [ ];

    defaultConfig = {
      alignTo = 16; # Default alignment
    };
  };

  # ==========================================================================
  # Convenience: Run binary blob directly
  # ==========================================================================

  # Helper to embed files as binary blobs
  #
  # Example:
  #   tools = [
  #     (native.binaryBlob.run {
  #       inputFiles = [ "usage.txt" ];
  #     })
  #   ];
  #
  # Then in C code:
  #   extern const unsigned char _binary_usage_txt_start[];
  #   extern const unsigned char _binary_usage_txt_end[];
  #   extern const size_t _binary_usage_txt_size;
  #
  generate =
    {
      inputFiles,
      root ? ./.,
      config ? { },
    }:
    binaryBlob.run { inherit inputFiles root config; };
}
