#include <cstdio>
#include <cstring>

// Symbols generated by the binary-blob tool
// These match the objcopy -I binary convention
extern "C" {
    extern const unsigned char _binary_usage_txt_start[];
    extern const unsigned char _binary_usage_txt_end[];
    extern const size_t _binary_usage_txt_size;

    extern const unsigned char _binary_license_txt_start[];
    extern const unsigned char _binary_license_txt_end[];
    extern const size_t _binary_license_txt_size;
}

void print_usage() {
    // Print the embedded usage text
    fwrite(_binary_usage_txt_start, 1, _binary_usage_txt_size, stdout);
}

void print_license() {
    // Print the embedded license text
    fwrite(_binary_license_txt_start, 1, _binary_license_txt_size, stdout);
}

int main(int argc, char* argv[]) {
    if (argc > 1) {
        if (strcmp(argv[1], "--help") == 0 || strcmp(argv[1], "-h") == 0) {
            print_usage();
            return 0;
        }
        if (strcmp(argv[1], "--license") == 0 || strcmp(argv[1], "-l") == 0) {
            print_license();
            return 0;
        }
    }

    printf("Binary blob example - embedded text files\n");
    printf("Usage size: %zu bytes\n", _binary_usage_txt_size);
    printf("License size: %zu bytes\n", _binary_license_txt_size);
    printf("\nRun with --help or --license to see embedded content\n");
    return 0;
}
